### ISSUE TITLE
Ошибка при запросе большой, огромной истории

### ISSUE THREAD

**Issue by xboston** [metahashorg/crypt_example_c#12]
В большинстве своём ошибка специфична и в ближайшее время для большинства адресов маловероятна, но она есть.
Есть адрес с `1 437 989`  транзакций, при попытке запросить их с лимитом и смещением нода плюётся ошибкой:
```
STD Exception: "std::bad_alloc" (/home/metahash-fullnode-client/src/task_handlers/fetch_history_handler_sync.cpp : 48)
```

Сам адрес: https://metawat.ch/address/0x005c754e1d2686a4742467ce2a01ddc9aab0c14d40a58e6526

**Comment by Nikitaempower** [comment]
@xboston Скажите, пожалуйста, Ваш вопрос все ещё актуален?

Если да, то какое значение для лимита и смещения Вы задаете?

**Comment by xboston** [comment]
Нет, проблема не актуальная с введением лимита на 9999 транзакций за раз.
