### ISSUE TITLE
Отсутствует метод fetch-balances

### ISSUE THREAD

**Issue by xboston** [metahashorg/crypt_example_c#15]
В сети он уже есть

**Comment by Nikitaempower** [comment]
https://github.com/metahashorg/metahash-fullnode-client/wiki/Usage#fetch-balance

Благодарим за Ваш вопрос. Метод в документации, выше. @xboston

**Comment by xboston** [comment]
@Nikitaempower в документации `fetch-balance`, который для одного адреса. Есть так же `fetch-balanceS`, для нескольких адресов сразу: https://xboston.github.io/metahash-api/#fetch-balances

**Comment by Andreano25** [comment]
Ок, добавим.

**Comment by Andreano25** [comment]
Метод добавится в ближайший релиз. 
У Вас есть ещё вопросы по данной теме?

**Comment by xboston** [comment]
Никак нет, с появлением методы вопрос закрыт.
